// mixin MockSearch {
//   static final List<String> searchedItems = [
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Dừng xe tại biển cấm dừng',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Dừng xe tại biển cấm dừng',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Dừng xe tại biển cấm dừng',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Dừng xe tại biển cấm dừng',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//     'Dừng xe tại biển cấm dừng',
//     'Vượt đèn đỏ',
//     'Tai nạn',
//   ];
//   static final List<String> frequentlySearchedItems = [
//     'Không mang giấy tờ',
//     'Xử phạt đèn đỏ',
//     'Không chấp hành hiệu lệnh của cảnh sát',
//     'Không mang giấy tờ',
//     'Xử phạt đèn đỏ',
//     'Không mang giấy tờ',
//     'Xử phạt đèn đỏ',
//     'Không chấp hành hiệu lệnh của cảnh sát',
//     'Không mang giấy tờ',
//     'Xử phạt đèn đỏ',
//   ];
// }
